//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace First_API_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity
    {
        public byte EntityId { get; set; }
        public string EntityName { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOnUtc { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOnUtc { get; set; }
    }
}
